exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "vendor", "Gemfile", "Gemfile.lock", "Guardfile", "assets.yml"]
highlighter: pygments

gems:
  - jekyll-sitemap

sass:
  style: :compressed
  sass_dir: assets/stylesheets

title: Brennan Moore
description: Building build web applications to help people go about their day in a more awesome way.
url: https://zamiang.com
production_url: http://www.zamiang.com
author:
  name: Brennan Moore
  email: brennanmoore@gmail.com
  github: zamiang
  twitter: zamiang
  gplus: 'https://plus.google.com/u/1/100884430802346698066/posts'
permalink: /:categories/:year/:month/:day/:title

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "smart"]

collections:
  projects:
    output: false
  publications:
    output: false
